# see https://pyup.io/docs/configuration/ for all available options
schedule: ''
update: false
requirements:
  # Requirements.txt contains nothing.
  - requirements/requirements.txt:
      update: False
      pin: False
  - requirements/requirements_synapse.txt:
      update: all
      pin: True
  - requirements/requirements_dev.txt:
      update: all
      pin: True
  - requirements/requirements_dep.txt:
      update: all
      pin: True
  - requirements/requirements_311.txt:
      update: all
      pin: True
