#!/bin/bash

docker buildx build \
  --platform=linux/amd64,linux/arm64/v8 \
  --tag "${IMAGE_NAME}" \
  --push \
  --file "${DOCKERFILE_PATH}" \
  --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  .
